llm_plan_idx_title = {
    "1": "Conduct Preliminary Client Consultation",
    "1.1": "Gather essential details about the prospective business",
    "1.2": "Identify immediate client concerns, goals, and timelines for formation",
    "1.3": "Clarify the client's budget and preferred level of formality in operations and governance",
    "1.4": "Determine whether the client anticipates seeking financing or additional investors",
    
    "2": "Clarify Business Goals and Stakeholder Roles",
    "2.1": "Identify short- and long-term objectives",
    "2.2": "Ascertain desired ownership percentages and permissible future transfers",
    "2.3": "Establish each stakeholder's expected contributions and responsibilities",
    "2.4": "Confirm any provisions for management or governance structures",
    
    "3": "Conduct State-Specific Research and Regulatory Check",
    "3.1": "Review relevant state statutes for entity formation requirements",
    "3.2": "Identify any specialized licensing or permitting requirements",
    "3.3": "Confirm naming restrictions and requirements for business entities",
    "3.4": "Consult state and local resources to confirm additional compliance steps",
    
    "4": "Provide Entity Selection Recommendations",
    "4.1": "Present suitable entity options based on liability, tax, and governance considerations",
    "4.2": "Discuss pros and cons of each structure",
    "4.3": "Advise on tax implications and refer the client to a tax professional if needed",
    "4.4": "Document the client's preferences for final confirmation",
    
    "5": "Perform Name Availability and Initial Registration Preparation",
    "5.1": "Conduct a name availability search with the Secretary of State",
    "5.2": "Advise on trademark or assumed name (DBA) filings if needed",
    "5.3": "Begin preparing basic formation documents",
    
    "6": "Draft and File Initial Formation Documents",
    "6.1": "Prepare and review the governing documents required by statute",
    "6.2": "File or arrange electronic submission of these documents with the appropriate state agency",
    "6.3": "Coordinate with the client to fulfill fee or payment requirements",
    "6.4": "Track and confirm official state recognition of the new entity",
    
    "7": "Complete Required Organizational and Tax Filings",
    "7.1": "Obtain an Employer Identification Number (EIN) from the IRS",
    "7.2": "Assist the client with local business license or permit applications",
    "7.3": "Address additional state tax registrations as required",
    
    "8": "Develop Internal Governance Framework",
    "8.1": "Confirm ownership structure details",
    "8.2": "Outline voting procedures, distribution policies, and transfer restrictions",
    "8.3": "Establish procedures for capital contributions and future financing",
    "8.4": "Determine management authority, decision-making powers, and conflict resolution protocols",
    
    "9": "Internal and External Review",
    "9.1": "Share drafts of governance documents with the client for comments",
    "9.2": "Consult with relevant colleagues for feedback on intricate provisions",
    "9.3": "Incorporate revisions based on feedback to align with client's goals",
    "9.4": "Validate final structure with relevant third parties if necessary",
    
    "10": "Draft and Finalize Operating Agreement",
    "10.1": "Incorporate all negotiated and agreed-upon ownership, management, and exit provisions",
    "10.2": "Verify that key agreements are accurately captured",
    "10.3": "Ensure state-specific formalities are included in the final document",
    "10.4": "Present the final Operating Agreement to the client for signatures"
}

human_plan_idx_title = {'1': 'Gather basic information, discover any underlying complexities',
 '1.1.1': 'Take Notes',
 '1.1': 'Ask Default Questions',
 '1.2.1': 'Ask follow-up questions',
 '1.2': 'Identify potential complications/follow-up questions',
 '1.3': 'Identify gaps in knowledge (#1)',
 '1.3.1': 'Search within appropriate realm of resources (#1)',
 '1.3.2': 'consult colleagues and obtain feedback',
 '2': 'Decide on recommendation to client(s), file forms',
 '2.1': 'Think about recommendations',
 '2.1.1': 'Consider counter-arguments/pros and cons',
 '2.2': 'Identify most important considerations/ Decide whether open/shut',
 '2.2.1': 'Identify whether you can reasonably represent interests of all clients in this case',
 '2.2.2': 'Communicate with clients if needed',
 '2.3': "Determine if you're doing business out of state (will need to file for each state)",
 '2.3.1': 'Search for relevant info about determining state jx',
 '2.3.1.1': 'Ask follow-up questions to client if needed',
 '2.3.2': 'Consult Secretary of State business filling resources (or similar) in relevant jx',
 '2.3.3': 'File forms personally',
 '2.3.4': 'Meet with client to file forms',
 '2.3.5': 'Write memo to client about how to file forms',
 '3': 'Send memo to client',
 '3.1': 'Write memo',
 '3.1.1': 'Obtain feedback from colleagues (#3)',
 '3.1.1.1': 'Revise memo',
 '3.1.2': 'Identify gaps in knowledge (#3)',
 '3.1.2.1': 'Search within appropriate realm of resources (#3)',
 '4': 'Write an Operating Agreement',
 '4.1': 'Search available template docs',
 '4.1.1': 'Edit selected template document to create operating agreement',
 '4.1.1.1': 'Obtain feedback from colleagues (#4)',
 '4.1.1.1.1': 'Revise operating agreement',
 '4.1.1.2': 'Compare with past agreements produced / documents used',
 '4.1.2': 'Identify applicable precendents',
 '4.1.2.1': 'Determine best (most well-crafted, most precise) and most relevant resources',
 '4.1.2.2': 'Identify various clauses, provisions that will be useful',
 '5': 'Tax Treatment of Entity [Island]',
 '5.1': 'Ask default tax questions of client',
 '5.2': 'Ask default tax questions of entity',
 '5.3': 'Identify gaps in knowledge',
 '5.4': 'Search within appropriate realm of resources',
 '5.5': 'Decide whether open/shut',
 '5.5.1': 'Advise on best entity form',
 '5.5.2': 'Refer out to tax professional if necessary'}

human_plan_node_list = ['1. Gather basic information, discover any underlying complexities',
 '1.1.1 Take Notes',
 '1.1 Ask Default Questions',
 '1.2.1 Ask follow-up questions',
 '1.2 Identify potential complications/follow-up questions',
 '1.3 Identify gaps in knowledge (#1)',
 '1.3.1 Search within appropriate realm of resources (#1)',
 '1.3.2 consult colleagues and obtain feedback',
 '2. Decide on recommendation to client(s), file forms',
 '2.1 Think about recommendations',
 '2.1.1 Consider counter-arguments/pros and cons',
 '2.2 Identify most important considerations/ Decide whether open/shut',
 '2.2.1 Identify whether you can reasonably represent interests of all clients in this case',
 '2.2.2 Communicate with clients if needed',
 "2.3 Determine if you're doing business out of state (will need to file for each state)",
 '2.3.1 Search for relevant info about determining state jx',
 '2.3.1.1 Ask follow-up questions to client if needed',
 '2.3.2 Consult Secretary of State business filling resources (or similar) in relevant jx',
 '2.3.3 File forms personally',
 '2.3.4 Meet with client to file forms',
 '2.3.5 Write memo to client about how to file forms',
 '3. Send memo to client',
 '3.1 Write memo',
 '3.1.1 Obtain feedback from colleagues (#3)',
 '3.1.1.1 Revise memo',
 '3.1.2 Identify gaps in knowledge (#3)',
 '3.1.2.1 Search within appropriate realm of resources (#3)',
 '4. Write an Operating Agreement',
 '4.1 Search available template docs',
 '4.1.1 Edit selected template document to create operating agreement',
 '4.1.1.1 Obtain feedback from colleagues (#4)',
 '4.1.1.1.1 Revise operating agreement',
 '4.1.1.2 Compare with past agreements produced / documents used',
 '4.1.2 Identify applicable precendents',
 '4.1.2.1 Determine best (most well-crafted, most precise) and most relevant resources',
 '4.1.2.2 Identify various clauses, provisions that will be useful',
 '5. Tax Treatment of Entity [Island]',
 '5.1 Ask default tax questions of client',
 '5.2 Ask default tax questions of entity',
 '5.3 Identify gaps in knowledge',
 '5.4 Search within appropriate realm of resources',
 '5.5 Decide whether open/shut',
 '5.5.1 Advise on best entity form',
 '5.5.2 Refer out to tax professional if necessary']

llm_plan_node_list = ['1',
 '1.1',
 '1.2',
 '1.3',
 '1.4',
 '2',
 '2.1',
 '2.2',
 '2.3',
 '2.4',
 '3',
 '3.1',
 '3.2',
 '3.3',
 '3.4',
 '4',
 '4.1',
 '4.2',
 '4.3',
 '4.4',
 '5',
 '5.1',
 '5.2',
 '5.3',
 '6',
 '6.1',
 '6.2',
 '6.3',
 '6.4',
 '7',
 '7.1',
 '7.2',
 '7.3',
 '8',
 '8.1',
 '8.2',
 '8.3',
 '8.4',
 '9',
 '9.1',
 '9.2',
 '9.3',
 '9.4',
 '10',
 '10.1',
 '10.2',
 '10.3',
 '10.4']

llm_plan_map_human_plan = {'1.1': '1.1 Ask Default Questions',
 '1.2': '1.1 Ask Default Questions',
 '1.3': '1.2 Identify potential complications/follow-up questions',
 '1.4': '1.2 Identify potential complications/follow-up questions',
 '2.1': '1.1 Ask Default Questions',
 '2.2': '1.2.1 Ask follow-up questions',
 '2.3': '1.2.1 Ask follow-up questions',
 '2.4': '1.2.1 Ask follow-up questions',
 '3.1': "2.3 Determine if you're doing business out of state (will need to file for each state)",
 '3.2': '2.3.1 Search for relevant info about determining state jx',
 '3.3': '2.3.1 Search for relevant info about determining state jx',
 '3.4': '2.3.1.1 Ask follow-up questions to client if needed',
 '4': '2. Decide on recommendation to client(s), file forms',
 '4.1': '2.1 Think about recommendations',
 '4.2': '2.1.1 Consider counter-arguments/pros and cons',
 '4.3': '5.5.2 Refer out to tax professional if necessary',
 '4.4': '5.1 Ask default tax questions of client',
 '5': '1.1 Ask Default Questions',
 '5.1': '1.1 Ask Default Questions',
 '5.2': '1.1 Ask Default Questions',
 '5.3': '2.3.3 File forms personally',
 '6': '2.3.4 Meet with client to file forms',
 '6.1': '2.3.4 Meet with client to file forms',
 '6.2': '2.3.4 Meet with client to file forms',
 '6.3': '2.3.5 Write memo to client about how to file forms',
 '6.4': '2.3.4 Meet with client to file forms',
 '7': '5.5.1 Advise on best entity form',
 '7.1': '5.5.1 Advise on best entity form',
 '7.2': '5.5.1 Advise on best entity form',
 '7.3': '5.5.1 Advise on best entity form',
 '8.1': '4.1.2 Identify applicable precendents',
 '8.2': '4.1.2 Identify applicable precendents',
 '8.3': '4.1.2.2 Identify various clauses, provisions that will be useful',
 '8.4': '4.1.2.2 Identify various clauses, provisions that will be useful',
 '9.1': '3. Send memo to client',
 '9.2': '3.1.1 Obtain feedback from colleagues (#3)',
 '9.3': '3.1.1.1 Revise memo',
 '9.4': '3.1.1 Obtain feedback from colleagues (#3)',
 '10.1': '4.1.1 Edit selected template document to create operating agreement',
 '10.2': '4.1.1 Edit selected template document to create operating agreement',
 '10.3': '4.1.1 Edit selected template document to create operating agreement',
 '10.4': '4.1.1.1 Obtain feedback from colleagues (#4)'}

human_plan_idx2title = {
    '1': '1. Gather basic information, discover any underlying complexities', 
    '1.1.1': '1.1.1 Take Notes', 
    '1.1': '1.1 Ask Default Questions', 
    '1.2.1': '1.2.1 Ask follow-up questions', 
    '1.2': '1.2 Identify potential complications/follow-up questions', 
    '1.3': '1.3 Identify gaps in knowledge (#1)', 
    '1.3.1': '1.3.1 Search within appropriate realm of resources (#1)', 
    '1.3.2': '1.3.2 consult colleagues and obtain feedback', 
    '2': '2. Decide on recommendation to client(s), file forms', 
    '2.1': '2.1 Think about recommendations', 
    '2.1.1': '2.1.1 Consider counter-arguments/pros and cons', 
    '2.2': '2.2 Identify most important considerations/ Decide whether open/shut', 
    '2.2.1': '2.2.1 Identify whether you can reasonably represent interests of all clients in this case', 
    '2.2.2': '2.2.2 Communicate with clients if needed', '2.3': "2.3 Determine if you're doing business out of state (will need to file for each state)", 
    '2.3.1': '2.3.1 Search for relevant info about determining state jx', '2.3.1.1': '2.3.1.1 Ask follow-up questions to client if needed', '2.3.2': '2.3.2 Consult Secretary of State business filling resources (or similar) in relevant jx', 
    '2.3.3': '2.3.3 File forms personally', '2.3.4': '2.3.4 Meet with client to file forms', '2.3.5': '2.3.5 Write memo to client about how to file forms', 
    '3': '3. Send memo to client', 
    '3.1': '3.1 Write memo', 
    '3.1.1': '3.1.1 Obtain feedback from colleagues (#3)', 
    '3.1.1.1': '3.1.1.1 Revise memo', '3.1.2': '3.1.2 Identify gaps in knowledge (#3)', 
    '3.1.2.1': '3.1.2.1 Search within appropriate realm of resources (#3)', 
    '4': '4. Write an Operating Agreement', '4.1': '4.1 Search available template docs', 
    '4.1.1': '4.1.1 Edit selected template document to create operating agreement', 
    '4.1.1.1': '4.1.1.1 Obtain feedback from colleagues (#4)', 
    '4.1.1.1.1': '4.1.1.1.1 Revise operating agreement', 
    '4.1.1.2': '4.1.1.2 Compare with past agreements produced / documents used', 
    '4.1.2': '4.1.2 Identify applicable precendents', 
    '4.1.2.1': '4.1.2.1 Determine best (most well-crafted, most precise) and most relevant resources', 
    '4.1.2.2': '4.1.2.2 Identify various clauses, provisions that will be useful', 
    '5': '5. Tax Treatment of Entity [Island]', 
    '5.1': '5.1 Ask default tax questions of client', 
    '5.2': '5.2 Ask default tax questions of entity', 
    '5.3': '5.3 Identify gaps in knowledge', 
    '5.4': '5.4 Search within appropriate realm of resources', 
    '5.5': '5.5 Decide whether open/shut', 
    '5.5.1': '5.5.1 Advise on best entity form', 
    '5.5.2': '5.5.2 Refer out to tax professional if necessary'
}